# Generated by Django 5.1.3 on 2024-12-04 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnoApp', '0002_equipamentos_documentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='senha',
            field=models.CharField(default='⠀', max_length=255),
        ),
    ]
